name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.3', '3.4', '4.0']

    steps:
      - uses: actions/checkout@v4

      - name: Install package
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips42 libvips-tools imagemagick libimlib2 libimlib2-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - env:
          VIPS_INFO: 1

        run: |
          identify -list format | grep HEIC
          VIPS_INFO=0 vips -l | grep heic
          bundle exec rake test
